POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "MehdiCarlito",
  "email": "testKafka22@example.com",
  "address": "allo street12",
  "dateOfBirth": "2003-07-16",
  "registeredDate": "2025-12-25"
}
